### ISSUE TITLE
AIMetatrader.com

### ISSUE THREAD

**Issue by ConsultingSecurty** [ScottFreeLLC/AlphaPy#20] opened 2018-02-08 15:14 UTC
Hello, 

i am a privat Person and i try to learn programming. I have a project to include Google AI latest to Metatrader4/5. Actually i want to inframe MT4/5 to a Domain called www.AIMetatrader.com and connect the MT4/5 to Python to include AlphaPy and open-source the result, as a free Web-Trading-AI. 

This is difficult for me, because i am not yet a programmer. I eater don't have Money to pay a programmer so i want to asking you for Partnership on this Project. I hope you are interested and agree.

**Comment by mrconway** [comment] 2018-02-08 15:23
Duplicate of #19

**Closed by mrconway** 2018-02-08 15:23 UTC
